---
title: STAT 5443, FINAL PROJECT
author: Ariel Mundo
date: "`r Sys.Date()`"
output:
    prettydoc::html_pretty:
    pdf_document: 
    theme: cayman
    css: styles.css
---
<style type="text/css">

p {
   font-size: 18px;
}
code.r{
  font-size: 14px;
}
pre {
  font-size: 18px
}
</style>



```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
library(prettydoc)
```

Library hdrm was installed following the directions from:
https://github.com/pbreheny/hdrm


```{r, loading data}

library(hdrm)
downloadData(Golub1999)
attachData(Golub1999)
```
http://www.sthda.com/english/articles/36-classification-methods-essentials/149-penalized-logistic-regression-essentials-in-r-ridge-lasso-and-elastic-net/#computing-penalized-logistic-regression
```{r, running analysis}
n=nrow(X)

#split in train and test sets

train_rows <- sample(1:n, n/2)
X.train <- X[train_rows, ]
X.test <- X[-train_rows, ]

y.train <- y[train_rows]
y.test <- y[-train_rows]

grid=10^seq(10,-2,length=100)
lasso.mod =glmnet (X.train, y.train, alpha = 1, lambda = grid)
plot(lasso.mod)

```

