---
title: STAT 5443, HW3
author: Ariel Mundo
date: "`r Sys.Date()`"
output:
    prettydoc::html_pretty:
    theme: cayman
    #css: styles.css
---
<style type="text/css">

p {
   font-size: 14px;
}
code.r{
  font-size: 14px;
}
pre {
  font-size: 14px
}
</style>



```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
library(prettydoc)
```

## PROBLEM 1
### GIBBS SAMPLER       
```{r, GIBBS SAMPLER}
rm(list = ls())

#binomial_beta_gibbs<- function(theta_init, s_init, niter){
alpha=2
beta_o=6.4
n=74
s_1=16
niter=1000
theta_init=s_1/n
s_init=s_1/n
  #theta = matrix(0,1,niter)
  theta=rep(NA,niter)
  #s=matrix(0,1,niter)
  s=rep(NA,niter)
  theta[1] = theta_init
  s[1]=s_init
  for(i in 2:niter){
    s[i] = rbinom(1,size=n,prob=theta[i-1])
    theta[i] = rbeta(1,alpha+s[i],beta_o+n-s[i])
  }
  #return(theta)
#}

#n=74
#s=16
#theta <- binomial_beta_gibbs(theta_init=n/s,s_init=n/s,niter=1000)

plot(theta,type="l", main='Traceplot for theta')
plot(s,type="l", main='Traceplot for s')
hist(s,freq=FALSE, main='Histogram for s')
print(paste('posterior median of theta:',median(theta), 'MLE estimate',s_1/n))
```
<div class = "blue">
 *The estimated posterior mean of* $\theta$ *is indeed to the maximum likelihood estimate of s/n .*
</div>
http://www.stat.cmu.edu/~brian/463-663/week10/Chapter%2004.pdf
https://bookdown.org/rdpeng/advstatcomp/gibbs-sampler.html


***

### PROBLEM 2


